### ISSUE TITLE
Uncaught TypeError: Cannot read property 'presenter' of null

### ISSUE THREAD

**Issue by a7madgamal** [miraks/ease-blink#8]
was just moving file from one panel to another by dragging the tap

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.4
**Thrown From**: [ease-blink](https://github.com/miraks/ease-blink) package, v0.5.1

### Stack Trace

Uncaught TypeError: Cannot read property 'presenter' of null

```
At /Users/mido/.atom/packages/ease-blink/lib/ease-blink.coffee:30

TypeError: Cannot read property 'presenter' of null
  at /Users/mido/.atom/packages/ease-blink/lib/ease-blink.coffee:30:21
  at /Users/mido/Downloads/Atom.app/Contents/Resources/app.asar/src/workspace.js:281:16
  at /Users/mido/Downloads/Atom.app/Contents/Resources/app.asar/src/workspace.js:338:18
  at Emitter.module.exports.Emitter.emit (/Users/mido/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/Users/mido/Downloads/Atom.app/Contents/Resources/app.asar/src/pane-container.js:375:27)
  at /Users/mido/Downloads/Atom.app/Contents/Resources/app.asar/src/pane-container.js:362:26
  at Emitter.module.exports.Emitter.emit (/Users/mido/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (/Users/mido/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:326:20)
  at Pane.module.exports.Pane.moveItemToPane (/Users/mido/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:415:19)
  at TabBarView.module.exports.TabBarView.moveItemBetweenPanes (/Users/mido/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:720:20)
  at TabBarView.module.exports.TabBarView.onDrop (/Users/mido/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:638:23)
  at space-pen-ul.<anonymous> (/Users/mido/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:3:61)
  at space-pen-ul.jQuery.event.dispatch (/Users/mido/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/Users/mido/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -6:34.5.0 core:save (atom-text-editor.editor.is-focused)
     -6:20.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -6:19.4.0 core:save (atom-text-editor.editor.is-focused)
     -5:44.8.0 find-and-replace:show (atom-text-editor.editor.is-focused)
  2x -5:36.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:30.9.0 project-find:show (atom-text-editor.editor.mini.is-focused)
     -5:29.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -5:29.6.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-seti-ui.find-visible)
     -5:07.6.0 core:copy (atom-text-editor.editor.is-focused)
     -5:04.7.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -4:57.3.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-seti-ui.find-visible)
  5x -4:45.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -3:57.8.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-seti-ui.find-visible)
  2x -3:48.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:48.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 18x -3:46.4.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-seti-ui.find-visible)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "base16-tomorrow-dark-theme"
    ],
    "disabledPackages": [
      "atom-beautify",
      "auto-indent",
      "local-history",
      "browser-plus",
      "git-history",
      "navigate",
      "run-command",
      "pathfinder",
      "autosave",
      "whitespace",
      "auto-detect-indentation",
      "tree-view-git-modified"
    ]
  },
  "ease-blink": {
    "blinkPeriod": 500
  }
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.3.0
auto-update-packages, v1.0.0
autocomplete-modules, v1.0.0
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.6
autocomplete-sass, v0.1.0
chary-tree-view, v0.2.3
code-links, v0.3.11
coffee-links, v0.1.0
ease-blink, v0.5.1
feedback, v0.38.0
git-tab-status, v1.9.2
highlight-selected, v0.10.1
seti-ui, v0.7.1
simple-drag-drop-text, v0.2.3
synced-sidebar, v0.4.0
tree-view-git-status, v0.1.1
useful-context-menu, v0.2.1

# Dev
No dev packages
```

**Comment by miraks** [comment]
Hey. Thanks for reporting this one. Fixed.
